<a href="https://colab.research.google.com/github/Bornitaadhikari/For-Practice/blob/main/NumPyBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.22.4'

In [ ]:
r1=np.array([[1,2,3,4],[5,6,8,8]]) # 2D array
r1

array([[1, 2, 3, 4],
       [5, 6, 8, 8]])

In [ ]:
r1.ndim # check the dimension

2

In [ ]:
r2=np.array([[[1,2,3,4],[2,3,4,5],[3,4,5,6]]]) #3d array
r2

array([[[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]]])

In [ ]:
r2.ndim

3

In [ ]:
r=np.array([1,2,3,3,4,5],ndmin=5) # creating higher dimensional array
r

array([[[[[1, 2, 3, 3, 4, 5]]]]])

In [ ]:
r.ndim

5

In [ ]:
r1

array([[1, 2, 3, 4],
       [5, 6, 8, 8]])

In [ ]:
r2

array([[[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]]])

In [ ]:
r4=np.array([1,2,3,4])
r4

array([1, 2, 3, 4])

In [ ]:
r4[2] - r4[0]

2

In [ ]:
r1 #access 2d array

array([[1, 2, 3, 4],
       [5, 6, 8, 8]])

In [ ]:
r1[1,]

array([5, 6, 8, 8])

In [ ]:
r1[1,2]-r1[0,3]

4

In [ ]:
r2

array([[[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]]])

In [ ]:
r4

array([1, 2, 3, 4])

In [ ]:
r4[0:3]

array([1, 2, 3])

In [ ]:
r4.dtype

dtype('int64')

In [ ]:
r5=np.array(["apple","orange","Bananna"])
r5.dtype

dtype('<U7')

In [ ]:
r6=np.array([1,2,3,4,4],dtype="float") #creating array with define datatype
r6

array([1., 2., 3., 4., 4.])

In [ ]:
r6.dtype

dtype('float64')

In [ ]:
r4   #copy

array([1, 2, 3, 4])

In [ ]:
r6=r4.copy()

In [ ]:
r6[0]=2
r6

array([2, 2, 3, 4])

In [ ]:
r6=r4.view()

In [ ]:
r6

array([1, 2, 3, 4])

In [ ]:
r6[3]=9
r6

array([1, 2, 3, 9])

In [ ]:
r6.shape #array shape

(4,)

In [ ]:
r2.shape

(1, 3, 4)

In [ ]:
r=np.array([1,2,3,4,5,6,6,7,7,8,5,6]) #reshape array 3d
rr=r.reshape(2,3,2)
rr

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[6, 7],
        [7, 8],
        [5, 6]]])